### PR TITLE
Vars

### PR DESCRIPTION
**Pull request by RekGRpth**

### CODE REVIEW

**Comment by max-lt** [comment]
Hi, thanks for contributing :)

I will integrate your 2 firsts commits, but as is, I will have to reject your PR for several reasons:
 - Pull request title means nothing.
 - You provided no description for it.
 - Your commits titles means nothing (except for "deffered jwt free").
 - Commits titles should start with a capital letter.
 - There is a link to a modified version of libjwt in the readme.
 - Your modifications relies on a edited version of libjwt (so the module cannot be build).
 - There is some code style issue:
   - There should have line breaks after if statements.
   - Code should not be inlined.
   - Code in conditional statements should be surrounded by brackets.
   
Why your custom "jwt_get_grants" is necessary ? Isn't it possible to do the same with [jwt_get_grant](https://github.com/benmcollins/libjwt/blob/master/libjwt/jwt.c#L598) ?

**Comment by RekGRpth** [comment]
> * Pull request title means nothing.

pull request adds variables as described in
https://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html#auth_jwt_claim_set
https://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html#auth_jwt_header_set
https://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html#variables

**Comment by RekGRpth** [comment]
> * Your modifications relies on a edited version of libjwt (so the module cannot be build).

not all! only https://github.com/max-lt/nginx-jwt-module/pull/16/commits/c9c2e9b1a9846d7c7d0c3542248f9c418dadf990

**Comment by RekGRpth** [comment]
> Why your custom "jwt_get_grants" is necessary ? Isn't it possible to do the same with [jwt_get_grant](https://github.com/benmcollins/libjwt/blob/master/libjwt/jwt.c#L598) ?

because I need to get value by sequence of nested json keys:
for example
```c
jwt_get_grants_json(jwt, NULL)
```
returns
```json
{"a":{"b":"c"}}
```
and I need to get "c" by keys "a" and "b"

**Comment by RekGRpth** [comment]
I, of course, can realize it by parsing json again, but it is bad

**Pull request closed without merging**
